OPAL/urls.py
from django.urls import path
from . import views

app_name="OPAL"

urlpatterns = [

    # Patient URLS
    path("patient/<int:id>/", views.patient_single, name="patient_single"),
    path("patient/", views.patient_list, name="patient_list"),
    path("patient/search/", views.patient_search, name="patient_search"),
    path("patient/create/", views.patient_create, name="patient_create"),
    path("patient/edit/<int:id>/", views.patient_edit, name="patient_edit"),
    path("patient/delete/<int:id>/", views.patient_delete, name="patient_delete"),
    
    # Therapist URLS
    path("therapist/<int:id>/", views.therapist_single, name="therapist_single"),
    path("therapist/", views.therapist_list, name="therapist_list"),
    path("therapist/search/", views.therapist_search, name="therapist_search"),
    path("therapist/create/", views.therapist_create, name="therapist_create"),
    path("therapist/edit/<int:id>/", views.therapist_edit, name="therapist_edit"),
    path("therapist/delete/<int:id>/", views.therapist_delete, name="therapist_delete"),
    
    # Therapy URLS
    path("therapy/<int:id>/", views.therapy_single, name="therapy_single"),
    path("therapy/list/patient/<int:id>/", views.therapy_list_patient, name="therapy_list_patient"),
    path("therapy/list/therapist/<int:id>/", views.therapy_list_therapist, name="therapy_list_therapist"),
    path("therapy/search/", views.therapy_search, name="therapy_search"),
    path("therapy/create/<int:id>/", views.therapy_create, name="therapy_create"),
    path("therapy/edit/<int:id>/", views.therapy_edit, name="therapy_edit"),
    path("therapy/delete/<int:id>/", views.therapy_delete, name="therapy_delete"),

    # Create Direct and Indirect Input URLS
    path("therapy/create/indirect_input/<int:id>/", views.indirect_input_create, name="indirect_input_create"),
    path("therapy/create/direct_input/<int:id>/", views.direct_input_create, name="direct_input_create"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('OPAL/', include('OPAL.urls', namespace="OPAL")),
    path('services/', include('services.urls', namespace="services")),
    path('', include('navigation.urls', namespace="navigation")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT);

OPAL/models.py
from django.db import models
from django.urls import reverse

class Team(models.Model):
    team_name = models.CharField(max_length=50)

    def __str__(self):
        return self.team_name

class Therapist(models.Model):

    # Enum for the therapist roles
    THERAPYASSISTANT = 'TA'
    OCCUPATIONTHERAPIST = 'OT'
    PHYSIOTHERAPY = 'PT'

    THERAPIST_ROLE_CHOICES = (
        (THERAPYASSISTANT, "Therapy Assistant"),
        (OCCUPATIONTHERAPIST, "Occupation Therapist"),
        (PHYSIOTHERAPY, "Physio Therapist"),
    )

    first_name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    therapist_role = models.CharField(
        max_length=2,
        choices=THERAPIST_ROLE_CHOICES,
        default=THERAPYASSISTANT  
    )
    band = models.IntegerField(default=1)
    assigned_team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.surname}: {self.id}"

    def get_absolute_url(self):
        return reverse('OPAL:therapist_single', args=[str(self.id)])

class Patient(models.Model):
    hospital_number = models.CharField(max_length=15, unique=True)
    first_name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    postcode = models.CharField(max_length=8)
    locality = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.surname}: {self.hospital_number}"
    
    def get_absolute_url(self):
        return reverse('OPAL:patient_single', args=[str(self.id)])

class DirectInput(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class IndirectInput(models.Model):
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

class Therapy(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    therapist = models.ForeignKey(Therapist, on_delete=models.CASCADE)
    rehab = models.BooleanField(default=False)
    direct_input = models.ForeignKey(DirectInput, blank=True, null=True, on_delete=models.SET_NULL)
    direct_time = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    indirect_input = models.ForeignKey(IndirectInput, blank=True, null=True, on_delete=models.SET_NULL)
    indirect_time = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Therapies"

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('OPAL:therapy_single', args=[str(self.id)])

OPAL/forms.py
from django.forms import ModelForm
from django import forms
from . models import Patient, Therapy, Therapist, DirectInput, IndirectInput

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = "__all__"

class TherapyForm(ModelForm):
    class Meta:
        model = Therapy
        fields = "__all__"
        exclude = ["patient"]

class TherapistForm(ModelForm):
    class Meta:
        model = Therapist
        fields = "__all__"

class DirectInputForm(ModelForm):
    class Meta:
        model = DirectInput
        fields = "__all__"

class IndirectInputForm(ModelForm):
    class Meta:
        model = IndirectInput
        fields = "__all__"

OPAL/views.py
from django.shortcuts import render
from . models import Patient, Therapy, Therapist
from django.db.models import Avg

def patient_single(request, id):
    patient = Patient.objects.get(id=id)
    therapies = Therapy.objects.filter(patient=id)
    return render(request, "OPAL/patient/single.html", {"patient": patient, "therapies": therapies})

def patient_list(request):
    patients = Patient.objects.all()
    return render(request, "OPAL/patient/list.html", {"patients": patients})

def therapy_single(request, id):
    therapy = Therapy.objects.get(id=id)
    return render(request, "OPAL/therapy/single.html", {"therapy": therapy})

def therapy_list(request):
    therapies = Therapy.objects.all()
    return render(request, "OPAL/therapy/list.html", {"therapies": therapies})

def therapist_list(request):
    therapist = Therapist.objects.all()
    return render(request, "OPAL/therapist/list.html", {"therapist": therapist})   

def therapist_single(request, id):
    therapist = Therapist.objects.get(id=id)
    therapies = Therapy.objects.filter(therapist=id)
    indirect_average = therapies.aggregate(Avg('indirect_time'))
    direct_average = therapies.aggregate(Avg('direct_time'))
    return render(request, "OPAL/therapist/single.html", {"therapist": therapist, "therapy": therapies, "direct_average": direct_average, "indirect_average": indirect_average})
 

OPAL/views/inputs.py
from django.shortcuts import render
from ..models import Therapy, Therapist
from ..forms import DirectInputForm, IndirectInputForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from ..models import Patient

@staff_member_required(login_url="/login/")
def direct_input_create(request, id):
    if request.method == "POST":
        form = DirectInputForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect("OPAL:therapy_create", id=id)
    else:
        form = DirectInputForm()
    return render(request, "OPAL/therapy/inputs/direct/create.html", {"form":form, "patient": Patient.objects.get(id=id)})


@staff_member_required(login_url="/login/")
def indirect_input_create(request, id):
    if request.method == "POST":
        form = IndirectInputForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect("OPAL:therapy_create", id=id)
    else:
        form = IndirectInputForm()
    return render(request, "OPAL/therapy/inputs/indirect/create.html", {"form":form, "patient": Patient.objects.get(id=id)})

OPAL/views/patient.py
from django.shortcuts import render
from .. models import Patient, Therapy
from .. forms import PatientForm
from django.db.models import Avg, Q
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

'''
    This view returns a single patinet object and the average
    direct and indirect times for therapies
'''
@login_required
def patient_single(request, id):
    patient = Patient.objects.get(id=id)
    therapies = Therapy.objects.filter(patient=id)
    indirect_average = therapies.aggregate(Avg('indirect_time'))
    direct_average = therapies.aggregate(Avg('direct_time'))
    return render(request, "OPAL/patient/single.html", {"patient": patient, "therapies": therapies, "direct_average": direct_average["direct_time__avg"], "indirect_average": indirect_average["indirect_time__avg"]})

'''
    The view returns a list of all patient before searching
'''
@login_required
def patient_list(request):
    return render(request, "OPAL/patient/list.html")


'''
    This view creating a patient object
'''
@staff_member_required(login_url="/login/")
def patient_create(request):
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect("OPAL:patient_single", id=task.id)
    else:
        form = PatientForm()
    return render(request, "OPAL/patient/create.html", {"form":form})

'''
    This view editing a patient object
'''
@staff_member_required(login_url="/login/")
def patient_edit(request, id):
    patient = Patient.objects.get(id=id)
    if request.method == "POST":
        form = PatientForm(request.POST, instance=patient)
        if form.is_valid():
            form.save()
            return redirect("OPAL:patient_single", id=id)
    else:
        data = {"hospital_number": patient.hospital_number, "first_name": patient.first_name,
                "surname": patient.surname, "date_of_birth": patient.date_of_birth,
                "postcode": patient.postcode, "locality": patient.locality}
        form = PatientForm(initial=data)
    return render(request, "OPAL/patient/edit.html", {"form":form, "patient": patient})

'''
    This view deleting a patient object
'''
@staff_member_required(login_url="/login/")
def patient_delete(request, id):
    patient = Patient.objects.get(id=id)
    patient.delete()
    return redirect('OPAL:patient_list')

'''
    This view searches for the patient object 
'''
@login_required
def patient_search(request):
    q = request.GET.get('q')
    messages = False
    object_list = Patient.objects.filter(
        Q(first_name__icontains=q) | Q(surname__icontains=q) | Q(hospital_number__icontains=q)
    )
    if len(object_list) == 0:
        messages = True
    return render(request, 'OPAL/patient/list.html', {"patients": object_list, "messages": messages})

OPAL/views/therapist.py
from django.shortcuts import render
from ..models import Therapy, Therapist
from ..forms import TherapistForm
from django.db.models import Avg, Q
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

'''
    The view returns a list of all therapists before searching
'''
@login_required
def therapist_list(request):
    return render(request, "OPAL/therapist/list.html")

'''
    This view returns a single therapist object and the average
    direct and indirect times for therapies
'''
@login_required
def therapist_single(request, id):
    therapist = Therapist.objects.get(id=id)
    therapies = Therapy.objects.filter(therapist=id)
    indirect_average = therapies.aggregate(Avg('indirect_time'))
    direct_average = therapies.aggregate(Avg('direct_time'))
    return render(request, "OPAL/therapist/single.html", {"therapist": therapist, "therapies": therapies, "direct_average": direct_average["direct_time__avg"], "indirect_average": indirect_average["indirect_time__avg"]})

'''
    This view creating a therapist object
'''
@staff_member_required(login_url="/login/")
def therapist_create(request):
    if request.method == "POST":
        form = TherapistForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect("OPAL:therapist_single", id=task.id)
    else:
        form = TherapistForm()
    return render(request, "OPAL/therapist/create.html", {"form":form})

'''
    This view editing therapist object along their band, 
    role and which team they assignd to 
'''
@staff_member_required(login_url="/login/")
def therapist_edit(request, id):
    therapist = Therapist.objects.get(id=id)

    if request.method == "POST":
        form = TherapistForm(request.POST, instance=therapist)
        if form.is_valid():
            form.save()
            return redirect("OPAL:therapist_single", id=id)
    else:
        data = {"first_name": therapist.first_name, "surname": therapist.surname, 
                "Therapist_role": therapist.therapist_role, "band": therapist.band, 
                "assigned_team": therapist.assigned_team}
        form = TherapistForm(initial=data)
    return render(request, "OPAL/therapist/edit.html", {"form":form, "therapist": therapist})

'''
    This view deleting therapist object 
'''
@staff_member_required(login_url="/login/")
def therapist_delete(request, id):
    therapist = Therapist.objects.get(id=id)
    therapist.delete()
    return redirect('OPAL:therapist_list')

'''
    This view searches for the therapist object 
'''
@login_required
def therapist_search(request):
    q = request.GET.get('q')
    messages = ""
    object_list = Therapist.objects.filter(
        Q(therapist_role__icontains=q) | Q(band__icontains=q) |Q(first_name__icontains=q) | Q(surname__icontains=q) | Q(id__icontains=q)
    )
    if len(object_list) == 0:
        messages = True
    return render(request, 'OPAL/therapist/list.html', {"therapists": object_list, "messages": messages})

OPAL/views/therapy.py
from django.shortcuts import render
from ..models import Therapy, Patient, Therapist
from ..forms import TherapyForm
from django.shortcuts import redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

'''
    The view returns a list of all therapy input before searching
'''
@login_required
def therapy_single(request, id):
    therapy = Therapy.objects.get(id=id)
    return render(request, "OPAL/therapy/single.html", {"therapy": therapy})

'''
    The view returns a list of all therapy input related to a given
    patient
'''
@login_required
def therapy_list_patient(request, id):
    patient = Patient.objects.get(id=id)
    therapies = Therapy.objects.filter(patient=patient)
    return render(request, "OPAL/therapy/list.html", {"patient": patient, "therapies": therapies})

'''
    The view returns a list of all therapy input related to a given
    therapist
'''
@login_required
def therapy_list_therapist(request, id):
    therapist = Therapist.objects.get(id=id)
    therapies = Therapy.objects.filter(therapist=therapist)
    return render(request, "OPAL/therapy/list.html", {"therapist": therapist, "therapies": therapies})

'''
    The view create a therapy input 
'''
@staff_member_required(login_url="/login/")
def therapy_create(request, id):
    patient = Patient.objects.get(id=id)
    if request.method == "POST":
        form = TherapyForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.patient = patient
            task = form.save()
            return redirect("OPAL:therapy_single", id=task.id)
    else:
        form = TherapyForm()
    return render(request, "OPAL/therapy/create.html", {"form":form, "patient": patient})

'''
    The view editing therapy input 
'''
@staff_member_required(login_url="/login/")
def therapy_edit(request, id):
    therapy = Therapy.objects.get(id=id)

    if request.method == "POST":
        form = TherapyForm(request.POST, instance=therapy)
        if form.is_valid():
            form.save()
            return redirect("OPAL:therapy_single", id=id)
    else:
        data = {"patient": therapy.patient, "therapist": therapy.therapist, 
                "rehab": therapy.rehab, "direct_input": therapy.direct_input, 
                "direct_time": therapy.direct_time, "indirect_input": therapy.indirect_input, "indirect_time": therapy.indirect_time}
        form = TherapyForm(initial=data)
    return render(request, "OPAL/therapy/edit.html", {"form":form, "therapy": therapy})

'''
    The view deleting therapy input 
'''
@staff_member_required(login_url="/login/")
def therapy_delete(request, id):
    therapy = Therapy.objects.get(id=id)
    therapy.delete()
    return redirect('OPAL:therapy_list')

'''
    The view searching for therapy input 
'''
@login_required
def therapy_search(request):
    q = request.GET.get('q')
    object_list = Therapy.objects.filter(
        Q(id__icontains=q) | Q(therapist__first_name__icontains=q) | Q(therapist__surname__icontains=q) | Q(patient__first_name__icontains=q) | Q(patient__surname__icontains=q)
    )
    return render(request, 'OPAL/therapy/list.html', {"therapies": object_list})

templates/OPAL/therapy/create.html
{% extends 'base.html' %}

{% block title %}Create Therapy{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container d-flex justify-content-center">
    <div class="form-for-nhs">
        <div class="card-header nhs-blue-text">
            <span class="ml-4"><strong>Create Therapy Form</strong></span>
        </div>
        <a style="width:100%;" class="btn btn-warning text-center p-2" href="{% url 'OPAL:direct_input_create' id=patient.id %}">Create Direct Input</a>
        <a style="width:100%;" class="btn btn-info text-center p-2" href="{% url 'OPAL:indirect_input_create' id=patient.id %}">Create Indirect Input</a>
        <form method="POST" class="form-group border font-weight-normal">
            {% csrf_token %}
            {{form|crispy}}
            <button style="width:100%;" type="submit" class="btn btn-primary nhs-blue-text text-center p-2">Create Therapy</button>
        </form>
    </div>
</div>
{% endblock %}

templates/OPAL/therapy/edit.html
{% extends 'base.html' %}

{% block title %}Update Therapy{{ therapy }}{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container d-flex justify-content-center">
    <div class="form-for-nhs">
        <div class="card-header nhs-blue-text">
            <span class="ml-4"><strong>Update Therapy Form</strong></span>
        </div>
        <form method="POST" class="form-group border font-weight-normal">
            {% csrf_token %}
            {{form|crispy}}
            <button style="width:100%;" type="submit" class="btn btn-primary nhs-blue-text text-center p-2">Update Therapy</button>
        </form>
    </div>
</div>
{% endblock %}

templates/OPAL/therapy/list.html
{% extends 'base.html' %}

{% block title %}Therapies{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
    <div>
        <div class="card-header nhs-blue-text">
            <h3>Find a Therapy</h3>
            <p>Search by Therapist name or ID</p>
            <div class="input-group mb-3">
                <form class="form-inline my-2 my-lg-0 flex" action="{% url 'OPAL:therapy_search' %}" method="get">
                    {% csrf_token %}
                    <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
        {% if therapies %}
            {% if patient %}
            <div class="card-header nhs-blue-text mt-4">
                <h3>Therapies for Patient: {{ patient }}</h3>
            </div>
            <a class="list-group-item btn btn-outline-primary text-left" href="{{ patient.get_absolute_url }}">Return to Patient</a>
            {% elif therapist %}
            <div class="card-header nhs-blue-text mt-4">
                <h3>Therapies for Therapist: {{ therapist }}</h3>
            </div>
            <a class="list-group-item btn btn-outline-primary text-left" href="{{ therapist.get_absolute_url }}">Return to Therapist</a>
            {% endif %}
            {% for therapy in therapies %}
            <div class="card font-weight-normal mt-3">
                <div class="card-header nhs-blue-text">
                Therapy ID: {{ therapy.id }}
                </div>
                <ul class="list-group list-group-flush">
                    <a class="list-group-item btn btn-outline-primary text-left" href="{{ therapy.get_absolute_url }}">View Therapy Detail</a>
                    {% if request.user.is_staff %}
                    <a class="list-group-item btn btn-outline-primary text-left" href="{% url 'OPAL:therapy_edit' id=therapy.id %}">Edit Therapy</a>
                    <form action= "{% url 'OPAL:therapy_delete' id=therapy.id %}" method="delete">
                    {% csrf_token %}
                    <button style="width:100%;" type="submit" class="list-group-item btn btn-outline-danger text-left">Delete Patient</button>
                    </form>
                    {% endif %}
                </ul>
            </div>
            {% endfor %}
        {% else %}
        <div class="card font-weight-normal mt-2">
            <div class="card-header nhs-blue-text">
                <h1>No Therapies Found</h1>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/OPAL/therapy/single.html
{% extends 'base.html' %}

{% block title %}{{ therapy.id }}{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
    <div class="card font-weight-normal">
        <div class="card-header nhs-blue-text">
            Patient: {{ therapy.patient }}
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item pl-3">Therapy ID: {{ therapy.id }}</li>
          <li class="list-group-item pl-3">Therapist: {{ therapy.therapist }}</li>
          <li class="list-group-item pl-3">
              <strong>Details:</strong><br>
              Therapy contained rehab: {{ therapy.rehab }}<br>
              Direct Assessment Type: {{ therapy.direct_input }}<br>
              Duration: {{ therapy.direct_time }}<br>
              Indirect Assessment Type: {{ therapy.indirect_input }}<br>
              Duration: {{ therapy.indirect_time }}<br>
          </li>


          {% if request.user.is_staff %}
          <a class="list-group-item pl-3 btn btn-outline-primary text-left" href="{% url 'OPAL:patient_single' id=therapy.patient.id %}">View Patient</a>
          <a class="list-group-item pl-3 btn btn-outline-primary text-left" href="{% url 'OPAL:therapist_single' id=therapy.therapist.id %}">View Therapist</a>
          <a class="list-group-item pl-3 btn btn-outline-warning text-left" href="{% url 'OPAL:therapy_edit' id=therapy.id %}">Edit Therapy</a>
          <form action= "{% url 'OPAL:therapy_delete' id=therapy.id %}" method="delete">
            {% csrf_token %}
            <button style="width:100%;" type="submit" class="list-group-item pl-3 btn btn-outline-danger text-left">Delete Therapy</button>
          </form>
          {% endif %}
        </ul>
    </div>
</div>
{% endblock %}