OPAL/urls.py
from django.urls import path
from . import views

app_name="OPAL"

urlpatterns = [

    # Patient URLS
    path("patient/<int:id>/", views.patient_single, name="patient_single"),
    path("patient/", views.patient_list, name="patient_list"),
    path("patient/search/", views.patient_search, name="patient_search"),
    path("patient/create/", views.patient_create, name="patient_create"),
    path("patient/edit/<int:id>/", views.patient_edit, name="patient_edit"),
    path("patient/delete/<int:id>/", views.patient_delete, name="patient_delete"),
    
    # Therapist URLS
    path("therapist/<int:id>/", views.therapist_single, name="therapist_single"),
    path("therapist/", views.therapist_list, name="therapist_list"),
    path("therapist/search/", views.therapist_search, name="therapist_search"),
    path("therapist/create/", views.therapist_create, name="therapist_create"),
    path("therapist/edit/<int:id>/", views.therapist_edit, name="therapist_edit"),
    path("therapist/delete/<int:id>/", views.therapist_delete, name="therapist_delete"),
    
    # Therapy URLS
    path("therapy/<int:id>/", views.therapy_single, name="therapy_single"),
    path("therapy/list/patient/<int:id>/", views.therapy_list_patient, name="therapy_list_patient"),
    path("therapy/list/therapist/<int:id>/", views.therapy_list_therapist, name="therapy_list_therapist"),
    path("therapy/search/", views.therapy_search, name="therapy_search"),
    path("therapy/create/<int:id>/", views.therapy_create, name="therapy_create"),
    path("therapy/edit/<int:id>/", views.therapy_edit, name="therapy_edit"),
    path("therapy/delete/<int:id>/", views.therapy_delete, name="therapy_delete"),

    # Create Direct and Indirect Input URLS
    path("therapy/create/indirect_input/<int:id>/", views.indirect_input_create, name="indirect_input_create"),
    path("therapy/create/direct_input/<int:id>/", views.direct_input_create, name="direct_input_create"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('OPAL/', include('OPAL.urls', namespace="OPAL")),
    path('services/', include('services.urls', namespace="services")),
    path('', include('navigation.urls', namespace="navigation")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT);

navigation/urls.py
from django.urls import path
from . import views

app_name = "navigation"

urlpatterns = [
    path('', views.home, name="home"),
    path('options/', views.options, name="options"),
]

navigation/models.py
from django.db import models

# Create your models here.

navigation/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'navigation/home.html')

def options(request):
    return render(request, 'navigation/options.html')

services/views/options.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from OPAL.models import Patient

@staff_member_required(login_url="/login/")
def add_service(request, id):
    patient = Patient.objects.get(id=id)
    return render(request, "services/add_service.html", {"patient": patient})

@staff_member_required(login_url="/login/")
def view_services(request, id):
    patient = Patient.objects.get(id=id)
    return render(request, "services/view_services.html", {"patient": patient})

templates/navigation/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <main class="container">
        <div class="FullWidthSplash m-5 d-flex flex-row justify-content-between">
            <div id="CQCroundup">
                <div class="span2 border p-3 bg-light">
                    <div class="HelpfulBox">
                        <div class="homepageCQC">
                            <div class="CQCcontent">
                                <img src="https://www.uhd.nhs.uk/uhd/templates/UHD-home/img/layout/cqc.png"
                                    alt="Care Quality Commission logo" class="CQCimg img-thumbnail">
                                <p>Bournemouth Hospital</p>
                                <p><strong>CQC overall rating</strong></p>
                                <p class="CQCrating btn btn-success">Good</p>
                                <p>18 June 2018 </p>
                                <a href="https://www.cqc.org.uk/location/RDZ20" class="CQCbutton" target="_blank">See
                                    the report</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/Span END-->
                <div class="span2 border p-3 ml-2 bg-light">
                    <div class="HelpfulBox">
                        <div class="homepageCQC">
                            <div class="CQCcontent">
                                <img src="https://www.uhd.nhs.uk/uhd/templates/UHD-home/img/layout/cqc.png"
                                    alt="Care Quality Commission logo" class="CQCimg img-thumbnail">
                                <p>Poole Hospital</p>
                                <p><strong>CQC overall rating</strong></p>
                                <p class="CQCrating btn btn-success">Good</p>
                                <p>18 June 2018 </p>
                                <a href="https://www.cqc.org.uk/location/RD300" class="CQCbutton" target="_blank">See
                                    the report</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/Span END-->
    
                <div class="span6">
                    <ul id="Dorsetroundup" class="thumbnails">
                        <li class="span4 ml-2">
                            <a href="https://ourdorset.nhs.uk" target="_blank" class="thumbnail">
                                <img src="https://www.uhd.nhs.uk/uhd/templates/UHD-home/img/layout/partners/our-dorset.png"
                                    alt="Our dorset, a partner of the hospital" class="CQCimg img-thumbnail">
                            </a>
                        </li>
    
                        <li class="span4 ml-2">
                            <a href="https://www.england.nhs.uk/personalisedcare/upc/ipc-for-veterans/veteran-aware-nhs-trusts/"
                                target="_blank" class="thumbnail">
                                <img src="https://www.uhd.nhs.uk/uhd/templates/UHD-home/img/layout/partners/veteran_aware.png"
                                    alt="Veteran aware, a partner of the hospital" class="CQCimg img-thumbnail">
                            </a>
                        </li>
    
                        <li class="span4 ml-2">
                            <a href="https://www.bournemouth.ac.uk/" target="_blank" class="thumbnail">
                                <img src="https://www.uhd.nhs.uk/uhd/templates/UHD-home/img/layout/partners/bournemouth-uni.png"
                                    alt="Bournemouth uni, a partner of the hospital" class="CQCimg img-thumbnail">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            
        </div>
            <!--container-->
        <!---->
        <!--Our Partners  /END================================================== -->




    </main>
{% endblock %}

templates/navigation/options.html
{% extends 'base.html' %}

{% block title %}Select Area{% endblock %}

{% block content %}

<div class="container d-flex justify-content-center">
  <div>
    <div class="card m-5 font-weight-normal">
        <div class="card-header nhs-blue-text">
          Patients
        </div>
        <ul class="list-group list-group-flush">
          <a class="list-group-item btn btn-outline-primary text-left" href="{% url 'OPAL:patient_create' %}">Insert a Patient</a>
          <a class="list-group-item btn btn-outline-primary text-left" href="{% url 'OPAL:patient_list' %}">Find a Patient</a>
        </ul>
    </div>
    <div class="card m-5 font-weight-normal">
        <div class="card-header nhs-blue-text">
          Therapists
        </div>
        <ul class="list-group list-group-flush">
          <a class="list-group-item btn btn-outline-primary text-left" href="{% url 'OPAL:therapist_create' %}">Insert a Therapist</a>
          <a class="list-group-item btn btn-outline-primary text-left" href="{% url 'OPAL:therapist_list' %}">Find a Therapist</a>
        </ul>
    </div>
  </div>
</div>
{% endblock %}